title: Wen-Dong Jiang's Homepage
page-top-title: Wen-Dong Jiang
top-section-bg-text: Welcome to Wen-Dong Jiang Homepage
home-subtitle: Wen-Dong Jiang&ensp;|&ensp;姜文棟
copyright-text: '&copy; Wen-Dong Jiang 2024-2026. All Rights Reserved.'
