title: Wen-Dong Jiang's Homepage
page-top-title: Wen-Dong Jiang
top-section-bg-text: Interpretable Machine Learning &middot; Smart City &middot; Multimodal Explanation
home-subtitle: Wen-Dong Jiang&ensp;|&ensp;蔣文東
copyright-text: '&copy; Wen-Dong Jiang 2024-2026. All Rights Reserved.'
